Fixed bug that caused migrations on models inheriting from GenericRelation to throw "AttributeError: 'GenericRel' object has no attribute 'field_name'"